[project]
name = "email-janitor"
version = "0.1.0"
description = "Email Janitor is an agentic solution that cleans up your email inbox."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
